import 'package:getit/core/models/item_model.dart';

List<Map> categories = [
  {
    'categoryName': 'Sneakers',
    'categoryImage': 'assets/images/running-shoe.png',
  },
  {
    'categoryName': 'Sandals',
    'categoryImage': 'assets/images/flip-flops.png',
  },
  {
    'categoryName': 'Boots',
    'categoryImage': 'assets/images/boot.png',
  },
  {
    'categoryName': 'High Heels',
    'categoryImage': 'assets/images/high-heels.png',
  },
  {
    'categoryName': "Men's Shoes",
    'categoryImage': 'assets/images/mens_shoe.png',
  },
  {
    'categoryName': 'Slippers',
    'categoryImage': 'assets/images/slippers.png',
  },
];
Map brandImages = {
  'Jordan': 'assets/images/jordan_logo.png',
  'Nike': 'assets/images/nike_logo.png',
  'Converse': 'assets/images/converse_logo.png',
  'Adidas': 'assets/images/adidas_logo.png',
  'Puma': 'assets/images/puma_logo.png',
};
List<ItemModel> items = [
  ItemModel(
      itemName: 'Velocity Stride',
      itemBrand: 'Puma',
      itemGroup: 'Sneakers',
      itemPrice: 250,
      itemImage: 'assets/images/velocity_stride.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Urban Pulse',
      itemBrand: 'Nike',
      itemGroup: 'Sneakers',
      itemPrice: 230,
      itemImage: 'assets/images/urban_pulse.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Adrenaline',
      itemBrand: 'Nike',
      itemGroup: 'Sneakers',
      itemPrice: 105,
      itemImage: 'assets/images/adrenaline.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Power Pace',
      itemBrand: 'Adidas',
      itemGroup: 'Sneakers',
      itemPrice: 25,
      itemImage: 'assets/images/power_pace.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Nike Flyknit',
      itemBrand: 'Nike',
      itemGroup: 'Sneakers',
      itemPrice: 25,
      itemImage: 'assets/images/nike_flyknit.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Retro Alternate',
      itemBrand: 'Jordan',
      itemGroup: 'Sneakers',
      itemPrice: 200,
      itemImage: 'assets/images/retro_alternate.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Chuck Taylor',
      itemBrand: 'Converse',
      itemGroup: "Men's Shoes",
      itemPrice: 55,
      itemImage: 'assets/images/chuck_taylor.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.2),
  ItemModel(
      itemName: 'Retro High',
      itemBrand: 'Jordan',
      itemGroup: 'Sneakers',
      itemPrice: 449.99,
      itemImage: 'assets/images/retro_high.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4.8),
  ItemModel(
      itemName: 'Jimmy Choo',
      itemBrand: 'Converse',
      itemGroup: 'High Heels',
      itemPrice: 105,
      itemImage: 'assets/images/jimmy_choo.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4),
  ItemModel(
      itemName: 'Heel Ankle',
      itemBrand: 'Nike',
      itemGroup: 'Boots',
      itemPrice: 35.95,
      itemImage: 'assets/images/heel_ankle.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 3),
  ItemModel(
      itemName: 'Adidas Continental',
      itemBrand: 'Adidas',
      itemGroup: 'Sneakers',
      itemPrice: 45,
      itemImage: 'assets/images/adidas_continental.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4),
  ItemModel(
      itemName: 'Beverly Bridal',
      itemBrand: 'Nike',
      itemGroup: 'High Heels',
      itemPrice: 20,
      itemImage: 'assets/images/beverly_bridal.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 3.5),
  ItemModel(
      itemName: 'WMN Retro High',
      itemBrand: 'Jordan',
      itemGroup: 'Sneakers',
      itemPrice: 120,
      itemImage: 'assets/images/wmn_retro_high.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Black Matt',
      itemBrand: 'Puma',
      itemGroup: 'High Heels',
      itemPrice: 35,
      itemImage: 'assets/images/black_matt.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 3),
  ItemModel(
      itemName: 'Puma X-Ray',
      itemBrand: 'Puma',
      itemGroup: 'Sneakers',
      itemPrice: 80,
      itemImage: 'assets/images/puma_xray.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Mayze Vaporous',
      itemBrand: 'Puma',
      itemGroup: 'Sneakers',
      itemPrice: 75.50,
      itemImage: 'assets/images/mayze_vaporous.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4),
  ItemModel(
      itemName: 'Stiletto Pumps',
      itemBrand: 'Nike',
      itemGroup: 'High Heels',
      itemPrice: 35,
      itemImage: 'assets/images/stiletto_pumps.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 3),
  ItemModel(
      itemName: 'Yeezy Sply',
      itemBrand: 'Adidas',
      itemGroup: 'Sneakers',
      itemPrice: 50,
      itemImage: 'assets/images/yeezy_sply.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Scott x Jordan',
      itemBrand: 'Jordan',
      itemGroup: "Men's Shoes",
      itemPrice: 590,
      itemImage: 'assets/images/scott_x_jordan.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4.5),
  ItemModel(
      itemName: 'Jordan Hex',
      itemBrand: 'Jordan',
      itemGroup: 'Sandals',
      itemPrice: 50,
      itemImage: 'assets/images/jordan_hex.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 3.5),
  ItemModel(
      itemName: 'More Uptempo',
      itemBrand: 'Nike',
      itemGroup: 'Sandals',
      itemPrice: 150,
      itemImage: 'assets/images/more_uptempo.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 5),
  ItemModel(
      itemName: 'SFB Field',
      itemBrand: 'Nike',
      itemGroup: 'Boots',
      itemPrice: 90.99,
      itemImage: 'assets/images/sfb_field.png',
      isRecommended: true,
      isFavorite: false,
      itemRating: 4),
  ItemModel(
      itemName: 'Nike Burrow',
      itemBrand: 'Nike',
      itemGroup: 'Slippers',
      itemPrice: 60,
      itemImage: 'assets/images/nike_burrow.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 5),
  ItemModel(
      itemName: 'Nike Asuna',
      itemBrand: 'Nike',
      itemGroup: 'Slippers',
      itemPrice: 45,
      itemImage: 'assets/images/nike_asuna.png',
      isRecommended: false,
      isFavorite: false,
      itemRating: 3.5),
];
